#!/usr/bin/env python3
"""
Copy Helper SQLite tables from topics.db into a PostgreSQL schema.

This is a preparation tool for a staged migration. It creates PostgreSQL tables
with compatible column names/types, loads data, creates simple indexes, and
prints source/target row counts. It does not change the application runtime.
"""

from __future__ import annotations

import argparse
import getpass
import os
import sqlite3
import sys
from dataclasses import dataclass
from typing import Iterable

try:
    import psycopg2
    from psycopg2 import sql
    from psycopg2.extras import execute_values
except ModuleNotFoundError:
    psycopg2 = None
    sql = None
    execute_values = None


@dataclass(frozen=True)
class ColumnInfo:
    name: str
    sqlite_type: str
    notnull: bool
    default: str | None
    pk_order: int


def sqlite_ident(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def pg_type(sqlite_type: str) -> str:
    typ = (sqlite_type or "").strip().upper()
    if "INT" in typ:
        return "BIGINT"
    if any(marker in typ for marker in ("CHAR", "CLOB", "TEXT", "VARCHAR")):
        return "TEXT"
    if any(marker in typ for marker in ("REAL", "FLOA", "DOUB")):
        return "DOUBLE PRECISION"
    if "BLOB" in typ:
        return "BYTEA"
    if "BOOL" in typ:
        return "BOOLEAN"
    if any(marker in typ for marker in ("NUM", "DEC")):
        return "NUMERIC"
    if "DATE" in typ or "TIME" in typ:
        return "TEXT"
    return "TEXT"


def default_sql(default: str | None, target_type: str) -> str:
    if default is None:
        return ""
    value = str(default).strip()
    if not value:
        return ""
    if target_type == "TEXT" and not value.startswith(("'", '"')) and value.upper() != "NULL":
        value = f"({value})::text"
    if target_type == "BOOLEAN" and value in {"0", "1"}:
        value = "false" if value == "0" else "true"
    return " DEFAULT " + value


def get_sqlite_tables(conn: sqlite3.Connection, selected: set[str] | None = None) -> list[str]:
    rows = conn.execute(
        """
        SELECT name
        FROM sqlite_master
        WHERE type = 'table'
          AND name NOT LIKE 'sqlite_%'
        ORDER BY name
        """
    ).fetchall()
    tables = [row["name"] for row in rows]
    if selected:
        missing = sorted(selected - set(tables))
        if missing:
            raise RuntimeError(f"SQLite tables not found: {', '.join(missing)}")
        tables = [table for table in tables if table in selected]
    return tables


def get_columns(conn: sqlite3.Connection, table: str) -> list[ColumnInfo]:
    rows = conn.execute(f"PRAGMA table_info({sqlite_ident(table)})").fetchall()
    return [
        ColumnInfo(
            name=row["name"],
            sqlite_type=row["type"] or "",
            notnull=bool(row["notnull"]),
            default=row["dflt_value"],
            pk_order=int(row["pk"] or 0),
        )
        for row in rows
    ]


def single_integer_pk(columns: list[ColumnInfo]) -> ColumnInfo | None:
    pk_cols = [col for col in columns if col.pk_order]
    if len(pk_cols) != 1:
        return None
    col = pk_cols[0]
    return col if "INT" in (col.sqlite_type or "").upper() else None


def create_schema(cur, schema: str) -> None:
    cur.execute(sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(sql.Identifier(schema)))


def drop_table(cur, schema: str, table: str) -> None:
    cur.execute(
        sql.SQL("DROP TABLE IF EXISTS {}.{} CASCADE").format(
            sql.Identifier(schema),
            sql.Identifier(table),
        )
    )


def create_table(cur, schema: str, table: str, columns: list[ColumnInfo]) -> None:
    identity_pk = single_integer_pk(columns)
    pk_cols = [col for col in columns if col.pk_order]
    column_defs = []

    for col in columns:
        target_type = pg_type(col.sqlite_type)
        parts: list[sql.Composable] = [sql.Identifier(col.name), sql.SQL(target_type)]
        if identity_pk and col.name == identity_pk.name:
            parts.append(sql.SQL("GENERATED BY DEFAULT AS IDENTITY"))
        if col.notnull and not col.pk_order:
            parts.append(sql.SQL("NOT NULL"))
        if not (identity_pk and col.name == identity_pk.name):
            default = default_sql(col.default, target_type)
            if default:
                parts.append(sql.SQL(default))
        if len(pk_cols) == 1 and col.pk_order:
            parts.append(sql.SQL("PRIMARY KEY"))
        column_defs.append(sql.SQL(" ").join(parts))

    if len(pk_cols) > 1:
        ordered_pk = sorted(pk_cols, key=lambda item: item.pk_order)
        column_defs.append(
            sql.SQL("PRIMARY KEY ({})").format(
                sql.SQL(", ").join(sql.Identifier(col.name) for col in ordered_pk)
            )
        )

    cur.execute(
        sql.SQL("CREATE TABLE IF NOT EXISTS {}.{} ({})").format(
            sql.Identifier(schema),
            sql.Identifier(table),
            sql.SQL(", ").join(column_defs),
        )
    )


def target_count(cur, schema: str, table: str) -> int:
    cur.execute(
        sql.SQL("SELECT COUNT(*) FROM {}.{}").format(
            sql.Identifier(schema),
            sql.Identifier(table),
        )
    )
    return int(cur.fetchone()[0])


def truncate_table(cur, schema: str, table: str) -> None:
    cur.execute(
        sql.SQL("TRUNCATE TABLE {}.{} RESTART IDENTITY CASCADE").format(
            sql.Identifier(schema),
            sql.Identifier(table),
        )
    )


def normalize_value(value, target_type: str):
    if target_type != "BOOLEAN" or value is None:
        return value
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return bool(value)
    if isinstance(value, str):
        normalized = value.strip().lower()
        if normalized in {"1", "true", "t", "yes", "y", "on"}:
            return True
        if normalized in {"0", "false", "f", "no", "n", "off", ""}:
            return False
    return bool(value)


def copy_table(
    sqlite_conn: sqlite3.Connection,
    pg_conn,
    schema: str,
    table: str,
    batch_size: int,
    columns_info: list[ColumnInfo],
) -> int:
    source_cur = sqlite_conn.execute(f"SELECT * FROM {sqlite_ident(table)}")
    columns = [desc[0] for desc in source_cur.description or []]
    target_types = {col.name: pg_type(col.sqlite_type) for col in columns_info}
    if not columns:
        return 0

    insert_sql = sql.SQL("INSERT INTO {}.{} ({}) VALUES %s").format(
        sql.Identifier(schema),
        sql.Identifier(table),
        sql.SQL(", ").join(sql.Identifier(col) for col in columns),
    )
    query = insert_sql.as_string(pg_conn)
    total = 0

    with pg_conn.cursor() as cur:
        while True:
            rows = source_cur.fetchmany(batch_size)
            if not rows:
                break
            values = [
                tuple(normalize_value(row[col], target_types.get(col, "TEXT")) for col in columns)
                for row in rows
            ]
            execute_values(cur, query, values, page_size=batch_size)
            total += len(values)
    return total


def reset_identity(cur, schema: str, table: str, columns: list[ColumnInfo]) -> None:
    identity_pk = single_integer_pk(columns)
    if not identity_pk:
        return
    relation_name = f'"{schema.replace(chr(34), chr(34) * 2)}"."{table.replace(chr(34), chr(34) * 2)}"'
    cur.execute("SELECT pg_get_serial_sequence(%s, %s)", (relation_name, identity_pk.name))
    row = cur.fetchone()
    sequence_name = row[0] if row else None
    if not sequence_name:
        return
    table_ref = sql.SQL("{}.{}").format(sql.Identifier(schema), sql.Identifier(table))
    cur.execute(
        sql.SQL(
            """
            SELECT setval(
                %s::regclass,
                COALESCE((SELECT MAX({pk}) FROM {table_ref}), 1),
                (SELECT COUNT(*) > 0 FROM {table_ref})
            )
            """
        ).format(pk=sql.Identifier(identity_pk.name), table_ref=table_ref),
        (sequence_name,),
    )


def create_indexes(sqlite_conn: sqlite3.Connection, cur, schema: str, table: str) -> None:
    index_rows = sqlite_conn.execute(f"PRAGMA index_list({sqlite_ident(table)})").fetchall()
    for index in index_rows:
        name = index["name"]
        if not name or name.startswith("sqlite_autoindex"):
            continue
        if index["origin"] == "pk" or int(index["partial"] or 0):
            continue
        col_rows = sqlite_conn.execute(f"PRAGMA index_info({sqlite_ident(name)})").fetchall()
        columns = [row["name"] for row in col_rows if row["name"]]
        if not columns:
            continue
        create = sql.SQL("CREATE {} INDEX IF NOT EXISTS {} ON {}.{} ({})").format(
            sql.SQL("UNIQUE") if int(index["unique"] or 0) else sql.SQL(""),
            sql.Identifier(name),
            sql.Identifier(schema),
            sql.Identifier(table),
            sql.SQL(", ").join(sql.Identifier(col) for col in columns),
        )
        cur.execute(create)


def sqlite_count(conn: sqlite3.Connection, table: str) -> int:
    return int(conn.execute(f"SELECT COUNT(*) FROM {sqlite_ident(table)}").fetchone()[0])


def parse_args(argv: Iterable[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Copy Helper SQLite topics.db into PostgreSQL schema")
    parser.add_argument("--sqlite", default=os.getenv("HELPER_SQLITE_DB", "topics.db"), help="Path to topics.db")
    parser.add_argument("--host", default=os.getenv("POSTGRES_HOST", "10.10.90.57"))
    parser.add_argument("--port", default=os.getenv("POSTGRES_PORT", "5432"))
    parser.add_argument("--database", default=os.getenv("POSTGRES_DB", "apo"))
    parser.add_argument("--user", default=os.getenv("POSTGRES_USER", "r_koledin"))
    parser.add_argument("--password", default=os.getenv("POSTGRES_PASSWORD", ""))
    parser.add_argument("--ask-password", action="store_true", help="Prompt for PostgreSQL password")
    parser.add_argument("--schema", default=os.getenv("POSTGRES_SCHEMA", "helper"))
    parser.add_argument("--table", action="append", dest="tables", help="Copy only this table; can be repeated")
    parser.add_argument("--drop-existing", action="store_true", help="Drop selected target tables before creating them")
    parser.add_argument("--truncate", action="store_true", help="Truncate target tables before loading rows")
    parser.add_argument("--append", action="store_true", help="Allow loading into non-empty target tables")
    parser.add_argument("--schema-only", action="store_true", help="Create schema/tables/indexes without copying data")
    parser.add_argument("--batch-size", type=int, default=1000)
    return parser.parse_args(list(argv))


def main(argv: Iterable[str] = sys.argv[1:]) -> int:
    args = parse_args(argv)
    if args.ask_password and not args.password:
        args.password = getpass.getpass(f"Password for {args.user}@{args.host}: ")

    sqlite_conn = sqlite3.connect(args.sqlite)
    sqlite_conn.row_factory = sqlite3.Row
    selected = set(args.tables or []) or None
    tables = get_sqlite_tables(sqlite_conn, selected)
    if not tables:
        print("No tables selected")
        return 1
    if psycopg2 is None:
        print("ERROR: psycopg2 is not installed. Install requirements.txt or psycopg2-binary.", file=sys.stderr)
        return 1

    pg_conn = psycopg2.connect(
        host=args.host,
        port=int(args.port),
        dbname=args.database,
        user=args.user,
        password=args.password,
    )
    pg_conn.autocommit = False

    try:
        with pg_conn.cursor() as cur:
            create_schema(cur, args.schema)
            for table in tables:
                columns = get_columns(sqlite_conn, table)
                if args.drop_existing:
                    drop_table(cur, args.schema, table)
                create_table(cur, args.schema, table, columns)
                if args.truncate:
                    truncate_table(cur, args.schema, table)
                existing = target_count(cur, args.schema, table)
                source_rows = sqlite_count(sqlite_conn, table)
                if existing and not (args.append or args.truncate or args.drop_existing or args.schema_only):
                    raise RuntimeError(
                        f"Target {args.schema}.{table} already has {existing} rows. "
                        "Use --truncate, --drop-existing, or --append."
                    )
                if not args.schema_only:
                    copied = copy_table(sqlite_conn, pg_conn, args.schema, table, args.batch_size, columns)
                    reset_identity(cur, args.schema, table, columns)
                else:
                    copied = 0
                create_indexes(sqlite_conn, cur, args.schema, table)
                after = target_count(cur, args.schema, table)
                print(f"{table}: sqlite={source_rows} copied={copied} postgres={after}")

        pg_conn.commit()
        print(f"Done. Schema: {args.schema}")
        return 0
    except Exception as exc:
        pg_conn.rollback()
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    finally:
        sqlite_conn.close()
        pg_conn.close()


if __name__ == "__main__":
    raise SystemExit(main())
